package storage

// Operation identifies a semantic action across a volume service, including
// its files, sessions, replication, and locks. The vocabulary spans Storage
// and its service capabilities independently of transport methods.
type Operation string

const (
	OpVolumeStat             Operation = "volume.stat"
	OpVolumeList             Operation = "volume.list"
	OpVolumeRead             Operation = "volume.read"
	OpVolumeSpace            Operation = "volume.space"
	OpVolumeSetAttr          Operation = "volume.set-attr"
	OpVolumeWrite            Operation = "volume.write"
	OpVolumeCreate           Operation = "volume.create"
	OpVolumeMkdir            Operation = "volume.mkdir"
	OpVolumeRemove           Operation = "volume.remove"
	OpVolumeRemoveDir        Operation = "volume.remove-dir"
	OpVolumeRename           Operation = "volume.rename"
	OpReplicationSubscribe   Operation = "replication.subscribe"
	OpReplicationResubscribe Operation = "replication.resubscribe"
	OpReplicationSnapshot    Operation = "replication.snapshot"
	OpReplicationCheckpoint  Operation = "replication.checkpoint"
	OpFileState              Operation = "file.state"
	OpFileSessionOpen        Operation = "file.session-open"
	OpFileStatus             Operation = "file.status"
	OpFileRenew              Operation = "file.renew"
	OpFileSessionClose       Operation = "file.session-close"
	OpFileStatNode           Operation = "file.stat-node"
	OpFileSetNodeAttr        Operation = "file.set-node-attr"
	OpFileRetain             Operation = "file.retain"
	OpFileRetainAt           Operation = "file.retain-at"
	OpFileCreateAndRetainAt  Operation = "file.create-and-retain-at"
	OpFileResetAndRetainAt   Operation = "file.reset-and-retain-at"
	OpFileReplaceAndRetainAt Operation = "file.replace-and-retain-at"
	OpFileReference          Operation = "file.reference"
	OpFileQueryAction        Operation = "file.query-action"
	OpFileCancelAction       Operation = "file.cancel-action"
	OpFileRetireRangeOwner   Operation = "file.retire-range-owner"
	OpFileStat               Operation = "file.stat"
	OpFileCheckObservation   Operation = "file.check-observation"
	OpFileRead               Operation = "file.read"
	OpFileWrite              Operation = "file.write"
	OpFileTruncate           Operation = "file.truncate"
	OpFileSetAttr            Operation = "file.set-attr"
	OpFileSetKind            Operation = "file.set-kind"
	OpFileLookupAt           Operation = "file.lookup-at"
	OpFileListAt             Operation = "file.list-at"
	OpFileRename             Operation = "file.rename"
	OpFileReplaceClaim       Operation = "file.replace-claim"
	OpFilePrepareRemoval     Operation = "file.prepare-removal"
	OpFileCancelPrepared     Operation = "file.cancel-prepared"
	OpFileDrainEntry         Operation = "file.drain-entry"
	OpFileCancelDrain        Operation = "file.cancel-drain"
	OpFileRangeSnapshot      Operation = "file.range-snapshot"
	OpFileReplaceRanges      Operation = "file.replace-ranges"
	OpFileWaitRanges         Operation = "file.wait-ranges"
	OpFileRetireRanges       Operation = "file.retire-ranges"
	OpFileSync               Operation = "file.sync"
	OpFileClose              Operation = "file.close"
	OpLockSessionEnrollment  Operation = "lock.session-enrollment"
	OpLockSessionOpen        Operation = "lock.session-open"
	OpLockSessionClose       Operation = "lock.session-close"
	OpLockOwnerCreate        Operation = "lock.owner-create"
	OpLockOwnerRetire        Operation = "lock.owner-retire"
	OpLockResolve            Operation = "lock.resolve"
	OpLockAcquire            Operation = "lock.acquire"
	OpLockRenew              Operation = "lock.renew"
	OpLockRelease            Operation = "lock.release"
	OpLockCancel             Operation = "lock.cancel"
	OpLockQueryAction        Operation = "lock.query-action"
	OpLockQueryGrant         Operation = "lock.query-grant"
	OpLockStatus             Operation = "lock.status"
)
