package storage

// Operation identifies a semantic action across a volume service, including
// its files, sessions, replication, and locks. The vocabulary spans Storage
// and its service capabilities independently of transport methods.
type Operation string

const (
	OpVolumeStat              Operation = "volume.stat"
	OpVolumeList              Operation = "volume.list"
	OpVolumeRead              Operation = "volume.read"
	OpVolumeSpace             Operation = "volume.space"
	OpVolumeSetAttr           Operation = "volume.set-attr"
	OpVolumeWrite             Operation = "volume.write"
	OpVolumeCreate            Operation = "volume.create"
	OpVolumeMkdir             Operation = "volume.mkdir"
	OpVolumeRemove            Operation = "volume.remove"
	OpVolumeRemoveDir         Operation = "volume.remove-dir"
	OpVolumeRename            Operation = "volume.rename"
	OpReplicationSubscribe    Operation = "replication.subscribe"
	OpReplicationResubscribe  Operation = "replication.resubscribe"
	OpReplicationSnapshot     Operation = "replication.snapshot"
	OpReplicationCheckpoint   Operation = "replication.checkpoint"
	OpFileSessionOpen         Operation = "file.session-open"
	OpFileStatus              Operation = "file.status"
	OpFileRenew               Operation = "file.renew"
	OpFileSessionClose        Operation = "file.session-close"
	OpFileStatNode            Operation = "file.stat-node"
	OpFileSetNodeAttr         Operation = "file.set-node-attr"
	OpFileOpen                Operation = "file.open"
	OpFileOpenNode            Operation = "file.open-node"
	OpFileAck                 Operation = "file.ack"
	OpFileStat                Operation = "file.stat"
	OpFileRead                Operation = "file.read"
	OpFileWrite               Operation = "file.write"
	OpFileTruncate            Operation = "file.truncate"
	OpFileSetAttr             Operation = "file.set-attr"
	OpFileSync                Operation = "file.sync"
	OpFileGetLock             Operation = "file.get-lock"
	OpFileSetLock             Operation = "file.set-lock"
	OpFileUnlock              Operation = "file.unlock"
	OpFileQueryLock           Operation = "file.query-lock"
	OpFileCancelLock          Operation = "file.cancel-lock"
	OpFileDropLocks           Operation = "file.drop-locks"
	OpFileClose               Operation = "file.close"
	OpLockSessionEnrollment   Operation = "lock.session-enrollment"
	OpLockSessionOpen         Operation = "lock.session-open"
	OpLockSessionClose        Operation = "lock.session-close"
	OpLockOwnerCreate         Operation = "lock.owner-create"
	OpLockOwnerRetire         Operation = "lock.owner-retire"
	OpLockResolve             Operation = "lock.resolve"
	OpLockAcquire             Operation = "lock.acquire"
	OpLockRenew               Operation = "lock.renew"
	OpLockRelease             Operation = "lock.release"
	OpLockCancel              Operation = "lock.cancel"
	OpLockQueryAction         Operation = "lock.query-action"
	OpLockQueryGrant          Operation = "lock.query-grant"
	OpLockStatus              Operation = "lock.status"
	OpWindowsState            Operation = "windows.state"
	OpWindowsEnable           Operation = "windows.enable"
	OpWindowsQueryActivation  Operation = "windows.query-activation"
	OpWindowsSessionOpen      Operation = "windows.session-open"
	OpWindowsSessionClose     Operation = "windows.session-close"
	OpWindowsRenew            Operation = "windows.renew"
	OpWindowsStatus           Operation = "windows.status"
	OpWindowsOpen             Operation = "windows.open"
	OpWindowsStat             Operation = "windows.stat"
	OpWindowsRead             Operation = "windows.read"
	OpWindowsWrite            Operation = "windows.write"
	OpWindowsTruncate         Operation = "windows.truncate"
	OpWindowsSetAttr          Operation = "windows.set-attr"
	OpWindowsList             Operation = "windows.list"
	OpWindowsReadLink         Operation = "windows.read-link"
	OpWindowsSetLink          Operation = "windows.set-link"
	OpWindowsRename           Operation = "windows.rename"
	OpWindowsSetDeletePending Operation = "windows.set-delete-pending"
	OpWindowsLockBatch        Operation = "windows.lock-batch"
	OpWindowsSync             Operation = "windows.sync"
	OpWindowsClose            Operation = "windows.close"
	OpWindowsQueryAction      Operation = "windows.query-action"
	OpWindowsCancelAction     Operation = "windows.cancel-action"
)
