-- The schema the migrations in migrations/ arrive at, as SQLite reports it, generated by
-- TestEveryRouteToTheCurrentSchemaArrivesAtTheSameOne. Nothing reads this file at runtime.
--
-- Edit the migrations, not this: run `go test ./packages/metastore/sqlite -update` to
-- record what they now produce. A diff here without a new migration beside it means a landed
-- migration was edited, which is the one thing the numbering forbids.

CREATE INDEX changes_by_namespace ON changes (namespace, position);

CREATE INDEX entries_by_node ON entries (node);

CREATE INDEX nodes_by_content ON nodes (content);

CREATE INDEX objects_by_state ON objects (namespace, state, created_sec);

-- index sqlite_autoindex_namespaces_1, which SQLite maintains itself

-- index sqlite_autoindex_objects_1, which SQLite maintains itself

CREATE TABLE changes (
	position      INTEGER PRIMARY KEY AUTOINCREMENT,
	namespace     INTEGER NOT NULL REFERENCES namespaces(id),
	kind          INTEGER NOT NULL,
	parent        INTEGER NOT NULL,
	name          BLOB,
	from_parent   INTEGER,
	from_name     BLOB,
	node          INTEGER,
	mode          INTEGER,
	size          INTEGER,
	atime_sec     INTEGER,
	atime_nsec    INTEGER,
	mtime_sec     INTEGER,
	mtime_nsec    INTEGER,
	content       TEXT,
	recorded_sec  INTEGER NOT NULL,
	recorded_nsec INTEGER NOT NULL
);

CREATE TABLE entries (
	namespace INTEGER NOT NULL REFERENCES namespaces(id),
	parent    INTEGER NOT NULL REFERENCES nodes(id),
	name      BLOB    NOT NULL,
	node      INTEGER NOT NULL REFERENCES nodes(id),
	PRIMARY KEY (namespace, parent, name)
) WITHOUT ROWID;

CREATE TABLE logs (
	namespace          INTEGER PRIMARY KEY REFERENCES namespaces(id),
	incarnation        TEXT    NOT NULL,
	committed_position INTEGER NOT NULL,
	trimmed_through    INTEGER NOT NULL,
	trimmed_by_age     INTEGER NOT NULL
);

CREATE TABLE namespaces (
	id   INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT    NOT NULL UNIQUE,
	root INTEGER NOT NULL,
	used INTEGER NOT NULL
);

CREATE TABLE nodes (
	id         INTEGER PRIMARY KEY AUTOINCREMENT,
	namespace  INTEGER NOT NULL REFERENCES namespaces(id),
	mode       INTEGER NOT NULL,
	size       INTEGER NOT NULL,
	atime_sec  INTEGER NOT NULL,
	atime_nsec INTEGER NOT NULL,
	mtime_sec  INTEGER NOT NULL,
	mtime_nsec INTEGER NOT NULL,
	content    TEXT REFERENCES objects(key)
);

CREATE TABLE objects (
	key          TEXT PRIMARY KEY,
	namespace    INTEGER NOT NULL REFERENCES namespaces(id),
	state        INTEGER NOT NULL,
	size         INTEGER NOT NULL,
	digest       BLOB,
	created_sec  INTEGER NOT NULL,
	created_nsec INTEGER NOT NULL
);

CREATE TABLE schema_version (version INTEGER NOT NULL);

CREATE TABLE sqlite_sequence(name,seq);

