-- The schema the migrations in ../schema/migrations/ arrive at, as SQLite reports it, generated by
-- TestEveryRouteToTheCurrentSchemaArrivesAtTheSameOne. Nothing reads this file at runtime.
--
-- Edit the migrations, not this: run `go test ./packages/metastore/sqlite/internal/integration -update` to
-- record what they now produce. A diff here without a new migration beside it means a landed
-- migration was edited, which is the one thing the numbering forbids.

CREATE INDEX changes_by_node_identity ON changes (
	CASE
	WHEN typeof(parent) = 'integer'
	AND typeof(from_parent) IN ('integer', 'null')
	AND typeof(node) IN ('integer', 'null')
	THEN 0 ELSE 1
	END,
	max(parent, coalesce(from_parent, 0), coalesce(node, 0))
);

CREATE INDEX changes_by_position_identity ON changes (
	CASE
	WHEN typeof(position) = 'integer' AND typeof(previous_position) = 'integer'
	THEN 0 ELSE 1
	END,
	max(position, previous_position)
);

CREATE INDEX changes_by_volume ON changes (volume, position);

CREATE INDEX delete_intents_by_node ON delete_intents (volume, node, outcome, intent);

CREATE INDEX entries_by_node ON entries (node);

CREATE INDEX entries_by_node_identity ON entries (
	CASE WHEN typeof(parent) = 'integer' AND typeof(node) = 'integer' THEN 0 ELSE 1 END,
	max(parent, node)
);

CREATE INDEX logs_by_change_identity ON logs (
	CASE
	WHEN typeof(committed_position) = 'integer' AND typeof(trimmed_through) = 'integer'
	THEN 0 ELSE 1
	END,
	max(committed_position, trimmed_through)
);

CREATE INDEX nodes_by_content ON nodes (content);

CREATE INDEX nodes_by_volume ON nodes (volume, id);

CREATE INDEX nodes_pending_unlink ON nodes (volume, id) WHERE pending_unlink = 1;

CREATE INDEX objects_by_state ON objects (volume, state, created_sec);

-- index sqlite_autoindex_objects_1, which SQLite maintains itself

-- index sqlite_autoindex_volumes_1, which SQLite maintains itself

CREATE INDEX volumes_by_root_identity ON volumes (
	CASE WHEN typeof(root) = 'integer' THEN 0 ELSE 1 END,
	root
);

CREATE TABLE backing_store (
	singleton INTEGER PRIMARY KEY CHECK (singleton = 1),
	store_id  TEXT    NOT NULL CHECK (store_id <> '')
) WITHOUT ROWID;

CREATE TABLE changes (
	position          INTEGER PRIMARY KEY AUTOINCREMENT,
	previous_position INTEGER NOT NULL,
	volume         INTEGER NOT NULL REFERENCES volumes(id),
	kind              INTEGER NOT NULL,
	parent            INTEGER NOT NULL,
	name              BLOB,
	from_parent       INTEGER,
	from_name         BLOB,
	node              INTEGER,
	size              INTEGER,
	atime_sec         INTEGER,
	atime_nsec        INTEGER,
	mtime_sec         INTEGER,
	mtime_nsec        INTEGER,
	content           TEXT,
	recorded_sec      INTEGER NOT NULL,
	recorded_nsec     INTEGER NOT NULL
	, node_kind INTEGER, birth_sec INTEGER, birth_nsec INTEGER, change_sec INTEGER, change_nsec INTEGER, metadata BLOB, link_target BLOB);

CREATE TABLE database_state (
	singleton         INTEGER PRIMARY KEY CHECK (singleton = 1),
	database_id       TEXT    NOT NULL CHECK (length(database_id) = 32),
	generation        INTEGER NOT NULL CHECK (generation >= 0),
	node_high_water   INTEGER NOT NULL CHECK (node_high_water >= 0),
	change_high_water INTEGER NOT NULL CHECK (change_high_water >= 0)
) WITHOUT ROWID;

CREATE TABLE delete_intents (
	intent TEXT PRIMARY KEY
	CHECK (length(CAST(intent AS BLOB)) = 32 AND intent NOT GLOB '*[^0-9a-f]*'),
	volume INTEGER NOT NULL,
	node INTEGER NOT NULL,
	parent INTEGER,
	name BLOB,
	reference BLOB NOT NULL CHECK (length(reference) = 16),
	request_hash BLOB NOT NULL CHECK (length(request_hash) = 32),
	if_empty INTEGER NOT NULL CHECK (if_empty IN (0, 1)),
	outcome INTEGER NOT NULL CHECK (outcome BETWEEN 1 AND 5),
	failure INTEGER,
	updated_sec INTEGER NOT NULL,
	updated_nsec INTEGER NOT NULL,
	CHECK ((parent IS NULL) = (name IS NULL)),
	CHECK (name IS NULL OR (
	typeof(name) = 'blob' AND length(name) > 0 AND
	name NOT IN (X'2e', X'2e2e') AND
	instr(name, X'2f') = 0 AND instr(name, X'00') = 0
)),
	CHECK ((outcome = 5) = (failure IS NOT NULL))
) WITHOUT ROWID;

CREATE TABLE entries (
	volume INTEGER NOT NULL REFERENCES volumes(id),
	parent    INTEGER NOT NULL REFERENCES nodes(id),
	name      BLOB    NOT NULL,
	node      INTEGER NOT NULL REFERENCES nodes(id),
	PRIMARY KEY (volume, parent, name)
) WITHOUT ROWID;

CREATE TABLE lease_recovery (
	singleton           INTEGER PRIMARY KEY CHECK (singleton = 1),
	database_id         TEXT NOT NULL,
	state_id            TEXT NOT NULL,
	accepted_generation INTEGER NOT NULL,
	accepted_nanos      INTEGER NOT NULL,
	prepared_generation INTEGER,
	prepared_nanos      INTEGER
) WITHOUT ROWID;

CREATE TABLE logs (
	volume          INTEGER PRIMARY KEY REFERENCES volumes(id),
	incarnation        TEXT    NOT NULL,
	committed_position INTEGER NOT NULL,
	trimmed_through    INTEGER NOT NULL,
	trimmed_by_age     INTEGER NOT NULL
);

CREATE TABLE nodes (
	id         INTEGER PRIMARY KEY AUTOINCREMENT,
	volume  INTEGER NOT NULL REFERENCES volumes(id),
	size       INTEGER NOT NULL,
	atime_sec  INTEGER NOT NULL,
	atime_nsec INTEGER NOT NULL,
	mtime_sec  INTEGER NOT NULL,
	mtime_nsec INTEGER NOT NULL,
	content    TEXT REFERENCES objects(key)
	, detached INTEGER NOT NULL DEFAULT 0, content_revision INTEGER NOT NULL DEFAULT 1, kind INTEGER NOT NULL DEFAULT 1, birth_sec INTEGER, birth_nsec INTEGER, change_sec INTEGER, change_nsec INTEGER, metadata BLOB NOT NULL DEFAULT X'52464d010000', link_target BLOB NOT NULL DEFAULT X'', pending_unlink INTEGER NOT NULL DEFAULT 0
	CHECK (pending_unlink IN (0, 1)), pending_generation INTEGER NOT NULL DEFAULT 0
	CHECK (pending_generation >= 0));

CREATE TABLE objects (
	key          TEXT PRIMARY KEY,
	volume    INTEGER NOT NULL REFERENCES volumes(id),
	state        INTEGER NOT NULL,
	size         INTEGER NOT NULL,
	digest       BLOB,
	created_sec  INTEGER NOT NULL,
	created_nsec INTEGER NOT NULL
);

CREATE TABLE schema_version (version INTEGER NOT NULL);

CREATE TABLE sqlite_sequence(name,seq);

CREATE TABLE volumes (
	id   INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT    NOT NULL UNIQUE,
	root INTEGER NOT NULL,
	used INTEGER NOT NULL
	, metadata_used INTEGER NOT NULL DEFAULT 0
	CHECK (typeof(metadata_used) = 'integer' AND metadata_used >= 0));

CREATE TRIGGER changes_metadata_delete AFTER DELETE ON changes BEGIN
	UPDATE volumes SET metadata_used = metadata_used - coalesce(length(OLD.metadata), 0) - coalesce(length(OLD.link_target), 0)
	WHERE id = OLD.volume;
	END;

CREATE TRIGGER changes_metadata_insert AFTER INSERT ON changes BEGIN
	UPDATE volumes SET metadata_used = metadata_used + coalesce(length(NEW.metadata), 0) + coalesce(length(NEW.link_target), 0)
	WHERE id = NEW.volume;
	END;

CREATE TRIGGER changes_metadata_update AFTER UPDATE OF metadata, link_target, volume ON changes BEGIN
	UPDATE volumes SET metadata_used = metadata_used - coalesce(length(OLD.metadata), 0) - coalesce(length(OLD.link_target), 0)
	WHERE id = OLD.volume;
	UPDATE volumes SET metadata_used = metadata_used + coalesce(length(NEW.metadata), 0) + coalesce(length(NEW.link_target), 0)
	WHERE id = NEW.volume;
	END;

CREATE TRIGGER nodes_metadata_delete AFTER DELETE ON nodes BEGIN
	UPDATE volumes SET metadata_used = metadata_used - length(OLD.metadata) - length(OLD.link_target)
	WHERE id = OLD.volume;
	END;

CREATE TRIGGER nodes_metadata_insert AFTER INSERT ON nodes BEGIN
	UPDATE volumes SET metadata_used = metadata_used + length(NEW.metadata) + length(NEW.link_target)
	WHERE id = NEW.volume;
	END;

CREATE TRIGGER nodes_metadata_update AFTER UPDATE OF metadata, link_target, volume ON nodes BEGIN
	UPDATE volumes SET metadata_used = metadata_used - length(OLD.metadata) - length(OLD.link_target)
	WHERE id = OLD.volume;
	UPDATE volumes SET metadata_used = metadata_used + length(NEW.metadata) + length(NEW.link_target)
	WHERE id = NEW.volume;
	END;

